### ISSUE TITLE
Remove all inline styles

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#13]
You should avoid inline styles like this:
<img id="logo" class="img-responsive img-rounded" src="img/logo.jpg" alt="man thinks" width="880" height="740" **style="display: inline"**>

So, remove all style="" attributes and move needed styles to style.css.

**Comment by RSmetanyuk** [comment]
how I can hide and unhide elements without style="display: inline" ?

**Comment by i10111pn** [comment]
https://stackoverflow.com/questions/14092940/javascript-how-to-hide-unhide-div

**Comment by RSmetanyuk** [comment]
там же окрім   visibility:hidden   пропонують   display:no.
Різниця між ними наступна https://www.w3schools.com/jsref/prop_style_visibility.asp
тобто display:no на відміну від visibility:hidden не лишає порожнього місця.
а щоб відобраззити елемент я міняю display:no на display: inline

**Comment by RSmetanyuk** [comment]
"display:no" instead of "visibility:hidden" does not leave free spase
