### ISSUE TITLE
Decrease column width

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#14]
Set 'Person A/B/C/D number/answer' columns width to 80px.
Remove 'Combination number' text and set a width of the first column to 10 px.

**Comment by RSmetanyuk** [comment]
If I try to change width of the last cell, all cells will be changed

**Comment by i10111pn** [comment]
your table has width 100%, change it to fix your issue

![image](https://user-images.githubusercontent.com/11459051/27262084-23d33822-5458-11e7-830e-ebbeac2925df.png)

**Comment by RSmetanyuk** [comment]
I do not set table width 100% anywhere. May be bootstrap set it.

**Comment by i10111pn** [comment]
Yes, bootstrap does this.

**Comment by RSmetanyuk** [comment]
To fix this I can find only this ways:
1)  add the empty column without borders
2)  wrap table in the "div class="col-sm-9"

**Comment by i10111pn** [comment]
Add class to 'table' tag.
And add style for this class in style.css
In this style set new width.

**Comment by RSmetanyuk** [comment]
It does not work. Commit "Tried change table width"

**Comment by i10111pn** [comment]
You have css error, see in the picture.
width: 665
665 of what? pixels?

![image](https://user-images.githubusercontent.com/11459051/27277606-754e94c8-54e7-11e7-92de-f5c35f675acf.png)
