### ISSUE TITLE
Add page header

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#18]
Add header like this.

![image](https://user-images.githubusercontent.com/11459051/27353305-39c3418a-560c-11e7-8424-d58a74cb5986.png)

Set the height of header above 55 -65px.

**Comment by RSmetanyuk** [comment]
That is you want?

**Comment by i10111pn** [comment]
Make it 100% wide.

**Comment by i10111pn** [comment]
Change number to logo image.
And remove logo image from content.
