### ISSUE TITLE
Add border to the table

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#20]
Add the border to the table, and set the widths of those borders - 2px.

![image](https://user-images.githubusercontent.com/11459051/27354199-70f540ce-560f-11e7-96fa-efbba20ddd5f.png)

**Comment by RSmetanyuk** [comment]
You mean bottom border of the header?

**Comment by i10111pn** [comment]
Yes. As you can see in the picture.

**Comment by i10111pn** [comment]
Do not forget to change border width from 3 to 2 px.
