### ISSUE TITLE
Add small screen support

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#23]
For screens smaller than 768px
http://getbootstrap.com/css/#grid (Extra small devices)

the page should look next

![image](https://user-images.githubusercontent.com/11459051/27355419-a3eda224-5613-11e7-992c-4635af90b05a.png)

**Comment by i10111pn** [comment]
On screens smaller than 768px
http://getbootstrap.com/css/#grid (Extra small devices)

Columns headers 
'Person A number' ... 'Person D number'
'Person A answer' ... 'Person D answer'

**should be renamed to**
'A number' ... 'D number'
'A answer' ... 'D answer'

**Also, columns headers it sould have 'font-size' 11px, and table should have 490px width**

![image](https://user-images.githubusercontent.com/11459051/27633185-dbee2902-5c06-11e7-9fe9-0ea4ed49b2e7.png)

**Comment by RSmetanyuk** [comment]
done

**Comment by i10111pn** [comment]
On 767px screen width:

![image](https://user-images.githubusercontent.com/11459051/27822713-4560b29a-60af-11e7-9251-307589170542.png)

**Comment by i10111pn** [comment]
On screen width smaller than 550px header has no 100% width

![image](https://user-images.githubusercontent.com/11459051/27822878-e36b2a92-60af-11e7-9ab0-e6cac9c6213c.png)

**Comment by i10111pn** [comment]
Your minimum supported resolution is 320x568 (iPhone5).

**Comment by RSmetanyuk** [comment]
iPhone5: 1136 x 640 px
iPhone4: 960 x 640 px

**Comment by RSmetanyuk** [comment]
In my Crome i have no problem with width of header:
![image](https://user-images.githubusercontent.com/29253760/27843503-0101ff1e-611d-11e7-83d2-dcbaee2e9ee6.png)

**Comment by i10111pn** [comment]
It is a resolution of a screen it is not the same as screen size.
Screen resolution is about screen quality, bigger resolution = good quality of the screen.

For example, my phone and monitor have the same resolution (full HD).
But the monitor is much bigger than a phone.

See:
http://viewportsizes.com/?filter=iPhone (real size)
https://goo.gl/Vxy2CF (resolution)

**Comment by i10111pn** [comment]
"In my Crome i have no problem with width of header:"

it should be 320, not 367.

**Comment by i10111pn** [comment]
Click on device toolbar in Chrome dev tools.
Select 'iPhone 5' in dropdown.

![image](https://user-images.githubusercontent.com/11459051/27843720-88559b5e-611f-11e7-8f5d-425c728980f7.png)

**Comment by RSmetanyuk** [comment]
done. commit "23. Fixed bugs"
