### ISSUE TITLE
Remove all !important from css

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#25]
Remove all **!important** from style.css if it possible.
If it not then describes this case in a comment here.

**Comment by RSmetanyuk** [comment]
I must leave three "!important" for three thick inner table borders. I think inner table borders made by bootstrap, so I need to set higher priority in css style.

**Comment by i10111pn** [comment]
Reopen this issue.

**1)**
th:first-child {
	width: 10px;
}
works without !important;
![image](https://user-images.githubusercontent.com/11459051/27510004-fefa073e-5910-11e7-9a5f-adf64efc0620.png)

**2)** Change css selector weight to get higher priority in style.css.

Example
#blockLeft .table>thead>tr>th {
	width: 80px;
	border-bottom: 10px solid;
}
![image](https://user-images.githubusercontent.com/11459051/27510080-72ef5364-5912-11e7-8b07-4e062833b067.png)

**Comment by i10111pn** [comment]
![image](https://user-images.githubusercontent.com/11459051/27590255-c3b9c31a-5b56-11e7-8ef9-ace81783e33b.png)

If you have a question or need help - describe it comment.
Do not add such labels.

**Comment by RSmetanyuk** [comment]
I can not set container width without "!important"

**Comment by i10111pn** [comment]
Skip it for awhile, I will check it.

**Comment by i10111pn** [comment]
Just increase selector weight
For example:

`body .container {
}`

**Comment by RSmetanyuk** [comment]
Done. https://github.com/RSmetanyuk/myapp/commit/400e6e52fa592b84007717a7db1e0a0f1284bbf5
