### ISSUE TITLE
Align main content by center

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#28]
X = Y

![image](https://user-images.githubusercontent.com/11459051/27477113-dcc0543c-5813-11e7-9a45-5fd3721ceb3f.png)

**Comment by i10111pn** [comment]
Reopen this issue.

X not equal Y

![image](https://user-images.githubusercontent.com/11459051/27509268-84f9f17e-5901-11e7-9e4b-9b69426f1bff.png)

**Comment by i10111pn** [comment]
Do not close issues.
Add comment **"Done. Need to be reviewed"** instead.

**Comment by i10111pn** [comment]
Also, check in settings if it possible to add me the ability to reopen issues.

**Comment by RSmetanyuk** [comment]
done
