### ISSUE TITLE
Click on 'Last' showing incorrect numbers of rows

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#31]
Select 'Combinations in page' to 10.
Click 'Last' button on the pagination.

It shows last 5 rows but should show last 10 rows.

![image](https://user-images.githubusercontent.com/11459051/27509198-0f2edca8-5900-11e7-8693-a07997a3658e.png)

**Comment by RSmetanyuk** [comment]
It is the bug of my way of realizing the task. The app works next way: 
1) the table rows are stored in the array;
2) "x combination in page" is the one element of the array.
Therefore the last element of the array is stored only:
1 row (for 5 combinations per page);
6 rows (for 10 combinations per page);
1 row (for 15 combinations per page);
16 rows (for 20 combinations per page).

**Comment by RSmetanyuk** [comment]
I can rework the app to store one row in one element of the array, and show full rows last page.

**Comment by RSmetanyuk** [comment]
256 combinations are not divided per "combinations in page" without remainder

**Comment by RSmetanyuk** [comment]
I can rework the app to store one row in one element of the array, and show full rows last page. But this will complicate the code and can cause problems with pagination.

**Comment by i10111pn** [comment]
Yes, rework it.

**Comment by RSmetanyuk** [comment]
done. But I have a new bug of changing "Combinations in page" before "Start" button was clicked.

**Comment by i10111pn** [comment]
I think the new bug will be fixed automatically with https://github.com/RSmetanyuk/myapp/issues/30 bug.

**Comment by RSmetanyuk** [comment]
Fixed a bug with locking the form before clicking the "Start" button
