### ISSUE TITLE
Change block's border

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#32]
Change border of header, main content, right content to similar like this

![image](https://user-images.githubusercontent.com/11459051/27509315-762128e2-5902-11e7-9bea-584085453b2d.png)

You can see it here https://v4-alpha.getbootstrap.com/components/card/#example

**Comment by RSmetanyuk** [comment]
I should use class="card" ?

**Comment by i10111pn** [comment]
The card is part of Bootstrap 4. 
You are using Bootstrap 3.
Just do a similar border (use inspect tool to see the styles of it).

**Comment by i10111pn** [comment]
Add top border also.

**Comment by i10111pn** [comment]
And make the border more similar to bootstrap 4 cards.

1. Open https://v4-alpha.getbootstrap.com/components/card/#example
2. Inspect styles of element with class "card".

**Comment by RSmetanyuk** [comment]
But I left gradient

**Comment by i10111pn** [comment]
Make borders rounded, see https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_border-radius

**Comment by RSmetanyuk** [comment]
The borders remained rounded, but I changed the rounding to a very small one, as in "Cards"
![image](https://user-images.githubusercontent.com/29253760/27917968-3a4fe20e-6276-11e7-85ca-e2c9d103e33d.png)

**Comment by i10111pn** [comment]
Increase it a little bit.

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Add top border main and right blocks.

![image](https://user-images.githubusercontent.com/11459051/27918585-0a889dc0-6278-11e7-804a-1e47d851bc2a.png)

**Comment by RSmetanyuk** [comment]
Done

**Comment by RSmetanyuk** [comment]
Done. Top border rounded.
