### ISSUE TITLE
Rework blocks

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#37]
**Header:**
Change < div class="container-fluid" id="header" > to < div class="container-fluid" **class="header"** >

**Main content:**
Add 10-15px padding.
Rename < div id="blockLeft" > to < div **class="main-content**" >
Add table border (see in the picture)

**Right block:**
Add 10-15px padding.
Rename < div id="blockRight" > to <div **class="right-sidebar"** >
Make button width 100%

![image](https://user-images.githubusercontent.com/11459051/27509684-1e7aa998-590b-11e7-8615-5134cd81e500.png)

**Comment by RSmetanyuk** [comment]
In one tag there can be only one class ?

For this css selector ".header" don't work:
< div class="container-fluid" class="header" >
   .....
</div>

For this work: 
<class="header" >
    < div class="container-fluid">
        .....
    </div>
</div>

**Comment by RSmetanyuk** [comment]
done

**Comment by i10111pn** [comment]
"In one tag there can be only one class ?"

You can have many classes in on element.
< div **class**="class-1 class-2 class-3" >

**Comment by i10111pn** [comment]
![image](https://user-images.githubusercontent.com/11459051/27591098-61fbad3e-5b59-11e7-909c-381817471472.png)

It should be a class, not id.

**Comment by i10111pn** [comment]
You forgot to add table border.
