### ISSUE TITLE
Add bootstrap pagination

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#4]
http://getbootstrap.com/components/#pagination

**Comment by i10111pn** [comment]
See working example here http://embed.plnkr.co/eheFSh/

**Comment by RSmetanyuk** [comment]
Here used "angular". Can I make pagination without "angular", which I don't learn yet?

**Comment by i10111pn** [comment]
It just example for better understanding.
Don't be confused by angular, you can do it without angular, just by using pure JavaScript.

**Comment by RSmetanyuk** [comment]
I replaced the pagination of a group of buttons, because I can't connect function to pagination

**Comment by RSmetanyuk** [comment]
I want to use paginations like this:
![image](https://user-images.githubusercontent.com/29253760/27491770-54498fe0-584c-11e7-8cf7-625ccd75408f.png)
It make this string:
<pagination total-items="totalItems" ng-model="currentPage" max-size="maxSize" class="pagination-sm" boundary-links="true" items-per-page="itemsPerPage"></pagination>

Can I do this, based on my current knowledge?

**Comment by RSmetanyuk** [comment]
I want to have not more then five page number buttons between "Previous" and "Next" buttons.

**Comment by RSmetanyuk** [comment]
I can write code to do this, but may be exist ready-made solution
