### ISSUE TITLE
Pagination active buttons

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#40]
After click on 'First' button, 'Previous' button is active.
Disable this button in this case.

After click on 'Last' button, 'Next' button is active.
Disable this button in this case.

See disabled button exemple here 
https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_button_active&stacked=h

**Comment by RSmetanyuk** [comment]
I knew about that, when I worked with pagination. But on disabled button "onclick" function still work. 
So I did so that by pressing the "previous" "next" buttons we can not go beyond the first and last page. Even if the "previous" button is inactive when we are on the first page,  onclick function will still work out, although we do not notice it.

**Comment by RSmetanyuk** [comment]
Should I do buttons deactivated?

**Comment by i10111pn** [comment]
Yes, you should.

**Comment by i10111pn** [comment]
Just add to your click handler additional 'if' statement.

```
if (<has class/attribue disabled >) {
  return;
}
```

**Comment by RSmetanyuk** [comment]
I used JQuery selector to set class "Disabled". To prevent run onclick on disabled buttons I used css:
.disabled {
    pointer-events: none;
}

**Comment by i10111pn** [comment]
It works.
Now rework it without using Jquery.

**Comment by i10111pn** [comment]
Also, make clicked button darker.
Because active button has the same background color as the main container.

![image](https://user-images.githubusercontent.com/11459051/27910090-45c022b2-625c-11e7-884d-ed5eb85f7f01.png)

**Comment by RSmetanyuk** [comment]
May I change content background color?

**Comment by RSmetanyuk** [comment]
I am difficult to change button background color

**Comment by i10111pn** [comment]
Sure, you can.

**Comment by RSmetanyuk** [comment]
Done

**Comment by RSmetanyuk** [comment]
Done
