### ISSUE TITLE
Add navigation buttons

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#41]
If the page has scroll.
Add buttons, that scrolls page to the page top/bottom.

See example here.
Here is only "go to the top" exemple.
https://codepen.io/rdallaire/pen/apoyx

Don't be confused by code, just see the example.

**Comment by i10111pn** [comment]
Also, add "go to the bottom" button.

**Comment by RSmetanyuk** [comment]
Done
