### ISSUE TITLE
Remove unnecessary libraries

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#43]
Remove **jquery.min.js** and **bootstrap.min.js**
You won't use it.

![image](https://user-images.githubusercontent.com/11459051/27772814-692efc92-5f72-11e7-8193-12f0ea0b7d9d.png)

**Comment by RSmetanyuk** [comment]
I use jQery for making pagination buttons disable.
I removed the second line.

**Comment by i10111pn** [comment]
Rework pagination without Jquery and remove jquery.min.js also.

**Comment by RSmetanyuk** [comment]
Done
