### ISSUE TITLE
Reset button behavior 

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#44]
**Steps to reproduce:**
 1. press 'Reset' button 

**Expected behavior:**
 'Rows per page' not selected (empty string).
 'Start from' input has no value.

**Current behavior:**  
'Rows per page' has '5' value.
'Start from' input has value.

![image](https://user-images.githubusercontent.com/11459051/27974387-7d4ca9e8-6366-11e7-999e-c3251f8ba731.png)

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Reset also 'Start from' input.
I will update bug description.

**Comment by RSmetanyuk** [comment]
Done
