### ISSUE TITLE
Table controls behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#45]
**Steps to reproduce:**
1. press 'Reset' button
2. click on 'Start from' input
3. select 'Rows per page'

**Expected behavior:** 
On steps 2 and 3 application should show red message "Please, press Start button"

**Current behavior:** 
Nothing is happening.

![image](https://user-images.githubusercontent.com/11459051/27974649-93ade11a-6367-11e7-9d16-7a29eae7fe0f.png)

**Comment by RSmetanyuk** [comment]
Should these fields be available for changing data, before click on "start" button?

**Comment by i10111pn** [comment]
No. It should show a red message "Please, press Start button" when you are trying to change 'Rows per page' or 'Start from'.

**Comment by RSmetanyuk** [comment]
Onmouseover doesn't work on disabled elements. Maybe error message will have appeared directly after pressing the reset button?

**Comment by i10111pn** [comment]
It should work on click, not on mouseover.

**Comment by RSmetanyuk** [comment]
Done. I think onmouseover is better onclick

**Comment by i10111pn** [comment]
It's bad user experience to show an error message on mouse move.

You want to show the error if you know that user wants to do that he currently can't do.
So, if a user is trying to click on 'Max rows per page ' or 'Start from' you can be sure that user is trying to perform currently not allowed actions.
But, when a user just moved his mouse, you can not be sure that he is trying to change 'Max rows per page ' or 'Start from' controls.

So, it is more user-friendly to show the error on click.

**Comment by RSmetanyuk** [comment]
Done. I changed onmouseover to onclick.

**Comment by i10111pn** [comment]
Select is not disabled:

![image](https://user-images.githubusercontent.com/11459051/28228827-d09de120-68e8-11e7-88b7-368a0f833543.png)

**Comment by RSmetanyuk** [comment]
Did you catch the moment the list was displayed?
But it becomes disabled after the click?

**Comment by i10111pn** [comment]
Yes, select becomes disabled after the click.
But you also should disable this first click.

**Comment by i10111pn** [comment]
And in 'Start from' input also.

**Comment by RSmetanyuk** [comment]
Done.

**Comment by RSmetanyuk** [comment]
Done. It was not easy!
