### ISSUE TITLE
'Start from' input behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#46]
**Steps to reproduce:**
1. Enter 1000 in 'Start from' input 

**Expected behavior:**
It should show error "There are only 256 rows"

**Current behavior:**
It changing the number to 252.

![image](https://user-images.githubusercontent.com/11459051/27974889-9c74b1c4-6368-11e7-843d-c8f0d7970662.png)

**Comment by RSmetanyuk** [comment]
Done
