### ISSUE TITLE
'Start from' input behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#47]
**Steps to reproduce:**
1. Enter 255 in 'Start from' input

**Expected behavior:**
It should show rows 255, 256.
And 'Rows per page' should not have any value (value is an empty string)

**Current behavior:**
It changing the number to 252.

![image](https://user-images.githubusercontent.com/11459051/27975062-52fa314e-6369-11e7-8de6-038d829d0363.png)

**Comment by RSmetanyuk** [comment]
Done
