### ISSUE TITLE
Merge 'Go to the top' and 'Go to the bottom' buttons

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#49]
**1.** Merge 'Go to the top' and 'Go to the bottom' buttons.
          Result button should be on the page bottom

![image](https://user-images.githubusercontent.com/11459051/27975454-e04bffea-636a-11e7-86ad-ec0aa520d113.png)

**2.** Try to control the speed of scrolling, when you pressing on of those buttons.

**Comment by RSmetanyuk** [comment]
Done
