### ISSUE TITLE
Rework statistic block for small screens

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#51]
Now on screens smaller than 974px statistic block looks like this

![image](https://user-images.githubusercontent.com/11459051/27976241-512c87a4-636e-11e7-8f9c-d90fdb8cd3c1.png)

Rework it to
![image](https://user-images.githubusercontent.com/11459051/27976214-30cccb72-636e-11e7-8dc2-3e2baa8c790a.png)

**Comment by RSmetanyuk** [comment]
I have to make a new table and hide the current one?

**Comment by i10111pn** [comment]
Yes.

**Comment by RSmetanyuk** [comment]
Done

**Comment by RSmetanyuk** [comment]
Done
