### ISSUE TITLE
Reset button should clear error message

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#52]
**Steps to reproduce:**
1. Enter 1000 in 'Start from' input.
2. The red error message appears. 
3. Press 'Reset' button.

**Expected behavior:**
The red error message disappears. 

**Current behavior:**
The red error message presents. 

![image](https://user-images.githubusercontent.com/11459051/28133133-a3bedfc6-6747-11e7-8f0f-4ef2547650e7.png)

**Comment by RSmetanyuk** [comment]
Done

**Comment by RSmetanyuk** [comment]
ClearED error message on reset
