### ISSUE TITLE
Start button behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#53]
**Steps to reproduce:**
1. Select to show 10 rows in 'Rows per page'.
2. Press 'Reset' button.
3. Press 'Start' button.

**Expected behavior:**
The table shows 5 rows as selected in 'Rows per page'

**Current behavior:**
The table shows 10 rows.

![image](https://user-images.githubusercontent.com/11459051/28133543-1423550c-6749-11e7-9283-652bf8c9ed06.png)

**Comment by RSmetanyuk** [comment]
Done
