### ISSUE TITLE
  Previous/Next pagination controls behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#54]
**Steps to reproduce:**
1. Enter 2 (or 3, 4, 5) in 'Start from' input

**Expected behavior:**
'Previous' button is disabled because the is no 5 previous rows, only 1 (2,3,4) rows.

**Current behavior:**
'Previous' button is enabled.

**The same behavior for 'Next' button.**

![image](https://user-images.githubusercontent.com/11459051/28135511-1c057722-674f-11e7-84ad-4170d5c93da5.png)

**Comment by RSmetanyuk** [comment]
I do not agree with this prposal. The Next and Previous buttons rewind the rows with a fixed number of rows (specified in "Rows per page"). But the ROWS in front (in the case of the Next button) and before (in the case of the Previous button) EXIST. And I think that with the Next and Previous buttons I must be able to see all rows on rewind, regardless of the fact that numbers of rows in the extreme positions can be smaller than "Rows per page".

**Comment by RSmetanyuk** [comment]
In the case of the information on the screen on click Previous I must see 1 row, then on click Next I must see 2-6 rows.

**Comment by RSmetanyuk** [comment]
This also applies to question # 55

**Comment by RSmetanyuk** [comment]
We can rename "Rows per page" to "Max rows per page"

**Comment by i10111pn** [comment]
Rename to "Max rows per page".
Then #54 and #55 will become invalid bugs.

**Comment by RSmetanyuk** [comment]
This is not implemented:
1) **Rename to "Max rows per page"**.
2) In the case of the information on the screen on click Previous I must see 1 row, **then on click Next I must see 2-6 rows**

**Comment by RSmetanyuk** [comment]
Done! Try:
In the case of the information on the screenshot above on click Previous I must see 1 row, then on click Next I must see 2-6 rows - FIXED
