### ISSUE TITLE
'Rows per page' select stop working

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#56]
**Steps to reproduce:**
1. Click 'Last' button.
2. Select to show all rows in 'Rows per page' select.

**Expected behavior:**
The table shows all rows

**Current behavior:**
The table shows 5 rows

![image](https://user-images.githubusercontent.com/11459051/28136245-af5bf31e-6751-11e7-9138-ed074f4cf934.png)

**Comment by RSmetanyuk** [comment]
It is not a bug. App shows all rows started from 252.

**Comment by i10111pn** [comment]
Since you have renamed 'Rows per page' select, this bug is not valid.
