### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#57]
**Steps to reproduce:**
1. Enter 0 (zero) in 'Start from' input.
2. Click outside the input.
3. 'You can start from "1" only' error message appears.
4. Move mouse over Start from' input.

**Expected behavior:**
The error message is not changed.

**Current behavior:**
'Please, press Start button' error message appears.

![image](https://user-images.githubusercontent.com/11459051/28184435-11a6fd3c-681c-11e7-8336-658cbe1324e1.png)

**Comment by RSmetanyuk** [comment]
Done
