### ISSUE TITLE
Reset button behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#58]
**Steps to reproduce:**
1. Enter 5 in 'Start from' input.
2. Press 'Reset' button.
3. Press 'Start' button.

**Expected behavior:**
The table rows are started from №1.
Because reset means reset to default and by default, when the app is starting, we show rows starting from the №1.

**Current behavior:**
The table rows are started from №5.

**Comment by RSmetanyuk** [comment]
Done
