### ISSUE TITLE
The 'First/Last' buttons behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#59]
**Case 1, Steps to reproduce:**
1. Open the app.

**Expected behavior:**
'First' button is disabled because it already shows rows from the beginning.

**Current behavior:**
The 'First' button is enabled.

![image](https://user-images.githubusercontent.com/11459051/28184939-10e5ae82-681e-11e7-8b0b-3d46065eaf62.png)
------------------------------------------

**Case 2, Steps to reproduce:**
1. Open the app.
2. Click 'Last' button.

**Expected behavior:**
The 'Last' button is disabled because it already shows the last rows.

**Current behavior:**
The 'Last' button is enabled.

![image](https://user-images.githubusercontent.com/11459051/28185015-6d84021a-681e-11e7-8c9b-0a5037d2901d.png)

**Note:**
The 'First' button should be disabled when rows are showed from the first row.
The 'Last' buttons should be disabled when the last row is showed.

**Comment by RSmetanyuk** [comment]
Done
