### ISSUE TITLE
'Max rows per page' behavior

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#60]
**Steps to reproduce:**
1. Select all in 'Max rows per page'.

**Expected behavior:**
'First/Last' buttons are disabled.

**Current behavior:**
'First/Last' buttons are enabled.

![image](https://user-images.githubusercontent.com/11459051/28189660-890b6ac6-682f-11e7-92ce-5fe558b5c4b6.png)

**Comment by RSmetanyuk** [comment]
"Start from" should be enabled?
What behavior of pagination buttons will be when we entered "Start from", they remain disabled?

**Comment by i10111pn** [comment]
Disable 'Start from' input also.

**Comment by RSmetanyuk** [comment]
Done
