### ISSUE TITLE
App enhancements

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#62]
**1.** Remove bold border from main table and statistic table.

**2.** Set blocks background color to #f7f7f9.

**3.** Clicked pagination button should be blue.
See bootstrap 'btn-default' class:
http://getbootstrap.com/components/#btn-dropdowns-single

**4.** Rework 'Max rows per page' with bootstrap selects.
http://getbootstrap.com/css/#selects 

**5.** Rework 'Start from' input with bootstrap input groups.
See http://getbootstrap.com/components/#input-groups-basic
Also, add '#' symbol from the left side of the input.

**6.** Reset button should be red.
See bootstrap 'btn-danger' class:
http://getbootstrap.com/components/#btn-dropdowns-single

**7.** Style eror message like bootstrap alert.
See bootstrap 'alert-danger' class.

**8.** Set blocks border radius to 5px.

**9.** Add '#' symbol to the table (1 in attached image)
Show bootstrap tooltip with text 'Combination number' on mouse hover on '#' symbol
See an example of bootstrap tooltip here:
http://getbootstrap.com/javascript/#tooltips-examples
**Note:** it requires bootstrap.js.

**10.** Update controls. (2 in attached image)

![image](https://user-images.githubusercontent.com/11459051/28228717-46565d76-68e8-11e7-8a72-82a2763bde99.png)

**Comment by i10111pn** [comment]
'2. Set blocks background color to #f7f7f9.'

Just set a background color, remove linear-gradient.

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
Looks like you missed add tooltip (subtask 9)

**Comment by RSmetanyuk** [comment]
![image](https://user-images.githubusercontent.com/29253760/28267366-7526b08a-6b02-11e7-9901-b3c5aa4337c1.png)

**Comment by i10111pn** [comment]
See an example of bootstrap tooltip here:
http://getbootstrap.com/javascript/#tooltips-examples

**Comment by RSmetanyuk** [comment]
Done. It was needed to add next:
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

**Comment by i10111pn** [comment]
Change tooltip position from right to left

![image](https://user-images.githubusercontent.com/11459051/28268386-cc2b8852-6b06-11e7-90e9-154408b9cbd5.png)

**Comment by RSmetanyuk** [comment]
I set it to the right to avoid this:
![image](https://user-images.githubusercontent.com/29253760/28274220-fe444b96-6b18-11e7-8490-50c6c22119f6.png)

**Comment by i10111pn** [comment]
Then show tooltip on the top

**Comment by RSmetanyuk** [comment]
Done
