### ISSUE TITLE
Navigation control 'go to the top' is not showed

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#63]
**Steps to reproduce:**
1. Open app.
2. Open chrome dev tools (F12).
3. Select to show dev tools from the right side.
![image](https://user-images.githubusercontent.com/11459051/28239349-240b5d9e-6973-11e7-96af-4c1b85a76135.png)

4. Click 'Toggle device tool bar'
![image](https://user-images.githubusercontent.com/11459051/28239374-ba4e0dc4-6973-11e7-91f9-650f509e8871.png)

5. Set device width and height to 700px.
![image](https://user-images.githubusercontent.com/11459051/28239386-f2dea3d8-6973-11e7-8365-f19329d59b36.png)

6.  Select to show 10 rows in 'Max rows per page'
7. Make navigation button appears (scroll down a little bit ) (related to #48 )
8. 'Go to the bottom' control appears.
9. Click 'Go to the bottom' control.
10. The page is scrolled to the bottom.

**Expected behavior:**
'Go to the top' control is visible.

**Current behavior:**
'Go to the top' control is no showed.

![image](https://user-images.githubusercontent.com/11459051/28239434-b3818cb8-6974-11e7-8744-bd0e5c683170.png)

**Comment by RSmetanyuk** [comment]
I think it fixed with #48
